#!/usr/bin/python
import os
import logging
import sys
from time import sleep

import plugins

log = logging.getLogger()
logging.basicConfig()
log.setLevel(logging.DEBUG)
debug = os.environ.get("debug", "0") == "1"


def p(msg):
    sys.stdout.write(msg)
    sys.stdout.flush()


def main(refreshinterval):
    while True:
        for screenitem in plugins.columns:
            p(screenitem() + "\t")

        print("")
        sleep(refreshinterval)


if __name__ == "__main__":
    if len(sys.argv) == 1:
        refreshinterval = 0.4
    else:
        try:
            refreshinterval = float(sys.argv[1])
        except:
            print("First argument may only be the refreshinterval in float format")

    main(refreshinterval)
